title: "김우 · 보안 기술 블로그"
description: "ISMS-P, NAC/DLP, AWS 보안, 로그분석, 운영 사례 아카이브"
url: "https://wmkim77.github.io"
timezone: Asia/Seoul

# 테마(원격)
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: air   # 스킨: air | dark | mint | neon | contrast | splash 등

# 플러그인
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-feed

# 검색/페이지네이션
search: true
search_full_content: true
paginate: 6
paginate_path: "/page:num/"

# 글 기본값(사이드 프로필 + TOC)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      toc: true
      toc_sticky: true

# 카테고리/태그 아카이브
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# 작성자 카드(사이드)
author:
  name: "김우"
  avatar: # 원하면 이미지 URL
  bio: "CISA · 보안 TF 리딩 · ISMS-P/NAC/DLP/AWS 보안"

collections:
  pages:
    output: true
    permalink: /:path/