title: "김우 · 보안 기술 블로그"
description: "ISMS-P, NAC/DLP, AWS 보안, 로그분석, 운영 사례 아카이브"
url: "https://wmkim77.github.io"

theme: minimal-mistakes-jekyll
timezone: Asia/Seoul

# MM 권장 플러그인
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-feed

paginate: 5
paginate_path: "/page:num/"

# 글 기본 옵션(TOC 켜고, 사이드에 작성자/네비)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      toc: true
      toc_sticky: true
      comments: false

# 카테고리/태그 아카이브
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# 작성자 정보(사이드 프로필 카드)
author:
  name: "김우"
  avatar: # 프로필 이미지 URL(선택)
  bio: "CISA · 보안 TF 리딩 · ISMS-P/NAC/DLP/AWS 보안"
